### ISSUE TITLE
geophone noise level?

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/common_issues#1]
### Background
- The noise level of the geophones, analyzed with 3-channel correlation method, are summarized as the attachment shows.  
- However, it seems that the amplitude of the spectra at 0.2Hz have a difference (by factor of 2), compared with the reference (ETMX-DP-GEOH/GEOV).

### Check list
- [ ] pre-amp gain in the reference is equal to 375.53*5./2, indeed?
- [ ] confirm where the difference by factor of 2 came from.
- [ ] check the feature of 3-channel correlation analysis.

### Question
- [ ] Does 3-channel correlation analysis make sense? (in terms of what..?)

### Notes
- proto(model) is from [1], but factor of 2 was multiplied to the magnitude, based on a report in [2].  
- The noise plots by 3-correlation analysis are reliable in the frequency range of 0.2Hz to 30Hz, according to the coherence plots.  
[1] https://granite.phys.s.u-tokyo.ac.jp/svn/LCGT/trunk/VIS/SuspensionControlModel/noise/GEOnoiseproto_vel.dat
[2] http://klog.icrr.u-tokyo.ac.jp/osl/?r=3893

### TODO (after the check)
- [ ] print in a file and upload it
- [ ] convert the unit into L/T/Y 
- [ ] add/compare ACC noise

**Comment by YoshinoriFujii** [comment]
> Check list
  pre-amp gain in the reference is equal to 375.53*5./2, indeed?  

Yes, it was. Since the _`GEOnoiseproto_vel.dat`_ includes the information of pre-amp gain already. No need to multiply factor of 2. The plot in _`GEOnoisecmp_vsDPGEO.pdf`_ is the correct one. [4]


> Question
  Does 3-channel correlation analysis make sense? (in terms of what..?)  

This correlation analysis would be done for the time series after multiplying the response function. Maybe the individual differences was issued here.
 Todo
  - [ ] measure the spectra with the proof mass fixed to the frame.
  - [ ]  analyze the time series after multiplying the response function. 


[4] [geophone_noise_spectra_summary.pdf](https://github.com/gw-vis/common_issues/files/2614112/geophone_noise_spectra_summary.pdf)

**Comment by YoshinoriFujii** [comment]
> analyze the time series after multiplying the response function.

Consequently:  
- Still difference by factor of 2 exists between the correlation analyzed ones and [1], GEOnoisecmp_vsDPGEO.pdf.
- the noise level of geo-4/5/6 would be better to be measured again

[Procedure]
- multiply

**Comment by YoshinoriFujii** [comment]
1. mass-fixed noise vs. noise analyzed with 3-channel correlation analysis

[geo_noise_comp_ETMY.pdf](https://github.com/gw-vis/common_issues/files/2626973/geo_noise_comp_ETMY.pdf)

- [ ] explain this discrepancy

**Comment by MiyoKouseki** [comment]
Can I close this issue?
