### ISSUE TITLE
ACC/GEO/LVDT noise levels

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/common_issues#3]
### Todo
- [ ] Do double check
- [ ] align the frequencies (do interpolation)
- [ ] model the measured data

### Attachments
**ACC, format: in [um/rtHz]**  
frequency[Hz] Signal(ACC1) Signal(ACC2) Signal(ACC3) Noise(ACC1) Noise(ACC2) Noise(ACC3)  
[acc_ITMX_measured_noise.txt](https://github.com/gw-vis/common_issues/files/2661656/acc_ITMX_measured_noise.txt)  
**Geophones, format: in [um/rtHz]**  
freduency [Hz] Signal1 Signal2 Signal3 Signal4 Noise1 Noise2 Noise3 Noise4
[geo_measured_SR_noise.txt](https://github.com/gw-vis/common_issues/files/2661657/geo_measured_SR_noise.txt)  
**LVDT, format:**  
Frequency[Hz] Noise(LVDT-H1)[um/rtHz] Noise(LVDT-H2)[um/rtHz] Noise(LVDT-H3)[um/rtHz] Noise(LVDT-L)[um/rtHz] Noise(LVDT-T)[um/rtHz] Noise(LVDT-Y)[urad/rtHz]
[LVDT_SR2_measured_noise.txt](https://github.com/gw-vis/common_issues/files/2661658/LVDT_SR2_measured_noise.txt)

**Comment by YoshinoriFujii** [comment]
Known issues:
- Geo/LVDT find noise when the stepping motor drivers are turned ON.

**Comment by MiyoKouseki** [comment]
Can I close this issue?
